version: '3'
services:

  web:
    image: webdevops/php-apache-dev:7.1
    volumes:
      - .:/var/www
    ports:
      - $HTTP_IP_PORT:80
    environment:
      - PHP_DISPLAY_ERRORS=true
      - WEB_DOCUMENT_ROOT=/var/www/web
      - PHP_DEBUGGER=xdebug
      - XDEBUG_REMOTE_HOST=$LOCAL_IP
      - XDEBUG_REMOTE_CONNECT_BACK=0
    links:
      - mariadb

  mariadb:
    image: mariadb:10.2
    ports:
      - $MARIADB_IP_PORT:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
